# action.yml
name: 'ocicl'
description: 'Publish an ocile artifact'
inputs:
  project-name:  # name of project
    description: 'Who to greet'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-name }}
