# action.yml
name: 'ocicl'
description: 'Publish an ocicl artifact'
inputs:
  project-name:  # name of project
    description: 'Project name'
    required: true
runs:
  using: "composite"
  steps:
    - run: curl -L -O "https://downloads.sourceforge.net/project/sbcl/sbcl/2.3.4/sbcl-2.3.4-x86-64-linux-binary.tar.bz2" && curl -L -O https://beta.quicklisp.org/quicklisp.lisp && tar -xf sbcl-2.3.4-x86-64-linux-binary.tar.bz2 && cd sbcl-2.3.4-x86-64-linux && ./install.sh --prefix=$HOME && cd .. && rm -rf sbcl-2.3.4-x86-64-linux-binary.tar.bz2 sbcl-2.3.4-x86-64-linux
      shell: bash
    - uses: actions/checkout@v3
    - run: |
        grep source README.org;
        if [ $? -eq 0 ]; then
          PROTOCOL=$(grep source README.org | awk '{ print $4 }' | cut -d: -f1) ;
          URI=$(grep source README.org | awk '{ print $4 }' | cut -d: -f2-) ;
          COMMIT=$(grep commit README.org | awk '{ print $4 }');
          mkdir src
          cd src
          case ${PROTOCOL} in
            git) git clone ${URI}
            ;;
            *) echo Unrecognized PROTOCOL ;
               exit 1;
            ;;
          esac;
          SRCDIR=$(ls)
          cd ${SRCDIR}
          git reset --hard ${COMMIT}
          rm -rf .git*
          cd ..
          tar cvfz $SRCDIR-$(date +%Y%m%d)-$COMMIT.tar.gz $SRCDIR
          echo \(require 'asdf\) \(push #p\"${SRCDIR}\" asdf:*central-registry*\) \(asdf:load-system \"cl-ppcre\"\) \(quit\) > ~/.sbclrc
          cat ~/.sbclrc
          ~/bin/sbcl
        fi
      shell: bash
    - run: $HOME/bin/sbcl --version
      shell: bash
