# action.yml
name: 'ocicl'
description: 'Publish an ocicl artifact'
inputs:
  project-name:  # name of project
    description: 'Project name'
    required: true
runs:
  using: "composite"
  steps:
    - run: curl -L -O "https://downloads.sourceforge.net/project/sbcl/sbcl/2.3.4/sbcl-2.3.4-x86-64-linux-binary.tar.bz2" && curl -L -O https://beta.quicklisp.org/quicklisp.lisp && tar -xf sbcl-2.3.4-x86-64-linux-binary.tar.bz2 && cd sbcl-2.3.4-x86-64-linux && ./install.sh --prefix=$HOME && cd .. && rm -rf sbcl-2.3.4-x86-64-linux-binary.tar.bz2 sbcl-2.3.4-x86-64-linux
      shell: bash
    - uses: actions/checkout@v3
    - run: |
        ls -l
        grep source README.org;
        if [ $* -eq 0 ]; then
          PROTOCOL=$(grep source README.org | awk '{ print $4 }' | cut -d: -f1) ;
          URI=$(grep source README.org | awk '{ print $4 }' | cut -d: -f2-) ;
          case $PROTOCOL in
            git) git clone ${URI}
            ;;
            *) error Unrecognized PROTOCOL
            ;;
          esac;
        fi
      shell: bash
    - run: $HOME/bin/sbcl --version
      shell: bash
